### PR TITLE
Improvements to docs page build

### PR DESCRIPTION
**Pull request by wende**
Continuation of #210 due to problems with the website:
- Page is too wide
- Top menu isn't center aligned with the rest of the page
- Elchemy-core changes that shouldn't be there

CC @Baransu

### CODE REVIEW

**Comment by wende** [comment]
@Baransu bump

**Comment by Baransu** [comment]
I haven't had time to look into it and I won't have time until next weekend unfortunately. 😞

**Comment by Baransu** [comment]
I'm not 100% sure how git submodules work but I've checkout `elchemy-core` to current commit that we're using on `master` branch of elchemy.

**Comment by wende** [comment]
@Baransu after updating the branch to master it should be desired behaviour then (no changes to core)

**Comment by wende** [comment]
The main cause of reverting this PR was the page width which causes horizontal scroll and was significantly impairing the experience on mobile devices

**Comment by Baransu** [comment]
The width is fixed.

What do you thing about adding `make build-page` to release rule so docs page will be always up to date with the latest release?

**Comment by wende** [comment]
@Baransu sounds good. I would add it right after `make release` in `.bump.sh` then

**Pull request merged**
